server:
  port: 8888
spring:
  application:
    name: "thiago-config-server"
  cloud:
    config:
      server:
        git:
          uri: https://github.com/renepont/spring-cloud-config
          default-label: master
          search-paths:
          - 'greeting-service'